// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiL3Uu-a4RFWnPUuySo-EUiDw9M5Q_R_Q',
    appId: '1:1017821197856:android:d2485beb0ca5cb6cb62e45',
    messagingSenderId: '1017821197856',
    projectId: 'rider-d206c',
    storageBucket: 'rider-d206c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgbF8mtJvVc6qzXFYHD29WAKLl3fexrjI',
    appId: '1:1017821197856:web:aff840b7b75cdafdb62e45',
    messagingSenderId: '1017821197856',
    projectId: 'rider-d206c',
    authDomain: 'rider-d206c.firebaseapp.com',
    storageBucket: 'rider-d206c.firebasestorage.app',
    measurementId: 'G-68Y1MD8XZV',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgbF8mtJvVc6qzXFYHD29WAKLl3fexrjI',
    appId: '1:1017821197856:web:408cd830639b7201b62e45',
    messagingSenderId: '1017821197856',
    projectId: 'rider-d206c',
    authDomain: 'rider-d206c.firebaseapp.com',
    storageBucket: 'rider-d206c.firebasestorage.app',
    measurementId: 'G-B5G5CF6EZN',
  );

}